from django.db import models

# Create your models here.
class MovieObj(models.Model):
    title = models.CharField(max_length=100,null=True)
    titleWords = models.CharField(max_length=500,null=True)
    year = models.CharField(max_length=50,null=True) 
    actor1 = models.CharField(max_length=50,null=True)
    actor2 = models.CharField(max_length=50,null=True)
    actor3 = models.CharField(max_length=50,null=True)
    director = models.CharField(max_length=50,null=True)
    keywords = models.CharField(max_length=500,null=True)
    genres = models.CharField(max_length=500,null=True)
    relevance = models.CharField(max_length=50,null=True) 
    country = models.CharField(max_length=50,null=True)
    language = models.CharField(max_length=50,null=True)
    criteria = models.CharField(max_length=1000,null=True)
    rating = models.CharField(max_length=50,null=True) 
    score = models.CharField(max_length=50,null=True) 
    movieID = models.CharField(max_length=50,null=True)
    poster = models.CharField(max_length=500,null=True)
    plot = models.CharField(max_length=9999,null=True)
    runtime = models.CharField(max_length=50,null=True) 
    numCritic = models.CharField(max_length=50,null=True) 
    gross = models.CharField(max_length=50,null=True) 
    fblikes = models.CharField(max_length=50,null=True) 
    budget = models.CharField(max_length=50,null=True) 
    numReviews = models.CharField(max_length=50,null=True) 
    IMDBScore = models.CharField(max_length=50,null=True) 
    awards = models.CharField(max_length=200,null=True)
    tomatoes = models.CharField(max_length=50,null=True) 
    metascore = models.CharField(max_length=50,null=True) 
    production = models.CharField(max_length=50,null=True)
    boxOffice = models.CharField(max_length=50,null=True)
    