from django.db import models

# Create your models here.
class MovieObj(models.Model):
    title = models.CharField(max_length=100,null=True)
    titleWords = models.CharField(max_length=500,null=True)
    year = models.IntegerField(null=True)
    actor1 = models.CharField(max_length=50,null=True)
    actor2 = models.CharField(max_length=50,null=True)
    actor3 = models.CharField(max_length=50,null=True)
    director = models.CharField(max_length=50,null=True)
    keywords = models.CharField(max_length=500,null=True)
    genres = models.CharField(max_length=500,null=True)
    relevance = models.IntegerField(null=True) 
    country = models.CharField(max_length=50,null=True)
    language = models.CharField(max_length=50,null=True)
    criteria = models.CharField(max_length=1000,null=True)
    rating = models.IntegerField(null=True) 
    score = models.IntegerField(null=True)     
    movieID = models.CharField(max_length=50,null=True)
    poster = models.CharField(max_length=500,null=True)
    plot = models.CharField(max_length=9999,null=True)
    runtime = models.IntegerField(null=True)
    numCritic = models.IntegerField(null=True)
    gross = models.IntegerField(null=True)
    fblikes = models.IntegerField(null=True)
    budget = models.IntegerField(null=True)
    numReviews = models.IntegerField(null=True)
    IMDBScore = models.DecimalField(max_digits=3, decimal_places=1, null=True)
    awards = models.CharField(max_length=200,null=True)
    tomatoes = models.IntegerField(null=True)
    metascore = models.IntegerField(null=True)
    production = models.CharField(max_length=50,null=True)
    boxOffice = models.CharField(max_length=50,null=True)
    