# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-19 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieobj',
            name='plot',
            field=models.CharField(max_length=9999, null=True),
        ),
        migrations.AddField(
            model_name='movieobj',
            name='poster',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='movieobj',
            name='runtime',
            field=models.IntegerField(null=True),
        ),
    ]
