# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 02:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0003_auto_20170328_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieobj',
            name='IMDBScore',
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
