# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-02 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('explore', '0004_movieobj_imdbscore'),
    ]

    operations = [
        migrations.AddField(
            model_name='movieobj',
            name='awards',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='movieobj',
            name='boxOffice',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movieobj',
            name='metascore',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movieobj',
            name='numCritic',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='movieobj',
            name='production',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='movieobj',
            name='tomatoes',
            field=models.IntegerField(null=True),
        ),
    ]
